# Generated by Django 5.1.7 on 2025-03-18 09:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100)),
                ('certificate_startdate', models.DateField(blank=True, null=True)),
                ('certificate_enddate', models.DateField(blank=True, null=True)),
                ('certificate_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
